name       : python-slugify
version    : 6.1.2
release    : 6
source     :
    - https://github.com/un33k/python-slugify/archive/refs/tags/v6.1.2.tar.gz : 3c093529760e45ced4f72a4a42d2028701b070e7a0a7acc79564ffeaf753fc4f
homepage   : https://github.com/un33k/python-slugify
license    : MIT
component  : programming.python
summary    : Returns unicode slugs
description: |
    A Python slugify application that handles unicode.
builddeps  :
    - python-text-unidecode
rundeps    :
    - python-text-unidecode
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test test.py
