name       : python-slugify
version    : 6.1.1
release    : 4
source     :
    - https://github.com/un33k/python-slugify/archive/refs/tags/v6.1.1.tar.gz : 895a4f78ed8203a3c147641ca798694c0264f054ec7f9fc8d234bac9ae7466f9
homepage   : https://github.com/un33k/python-slugify
license    : MIT
component  : programming.python
summary    : Returns unicode slugs
description: |
    A Python slugify application that handles unicode.
builddeps  :
    - python-text-unidecode
rundeps    :
    - python-text-unidecode
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test test.py
