name       : python-slugify
version    : 8.0.1
release    : 8
source     :
    - https://github.com/un33k/python-slugify/archive/refs/tags/v8.0.1.tar.gz : a1fab6eaa4df99975afdc45899e968a5d85d4d494468d833c540dffeefee423d
homepage   : https://github.com/un33k/python-slugify
license    : MIT
component  : programming.python
summary    : Returns unicode slugs
description: |
    A Python slugify application that handles unicode.
builddeps  :
    - python-text-unidecode
rundeps    :
    - python-text-unidecode
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test test.py
