name       : python-slugify
version    : 5.0.2
release    : 3
source     :
    - https://github.com/un33k/python-slugify/archive/refs/tags/5.0.2.tar.gz : 66067dbd30ca3d3d412e7ae1c616ba24c0cd0c8325cbeae468edae6b23e3c544
homepage   : https://github.com/un33k/python-slugify
license    : MIT
component  : programming.python
summary    : Returns unicode slugs
description: |
    A Python slugify application that handles unicode.
builddeps  :
    - python-text-unidecode
rundeps    :
    - python-text-unidecode
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test test.py
